# Generated by Django 4.2.1 on 2023-05-19 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal',
            options={'ordering': ['admission_date'], 'verbose_name': 'Animal'},
        ),
        migrations.AlterModelOptions(
            name='animalclass',
            options={'verbose_name': 'AnimalClass'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Country'},
        ),
        migrations.AlterModelOptions(
            name='fodder',
            options={'verbose_name': 'Fodder'},
        ),
        migrations.AlterModelOptions(
            name='placement',
            options={'verbose_name': 'Placement'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Post'},
        ),
        migrations.AlterModelOptions(
            name='species',
            options={'verbose_name': 'Species'},
        ),
        migrations.AlterModelOptions(
            name='staffer',
            options={'verbose_name': 'Staffer'},
        ),
    ]
