# Generated by Django 4.2.1 on 2023-05-19 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_animal_options_alter_animalclass_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal',
            options={'ordering': ['admission_date'], 'verbose_name': 'Animal', 'verbose_name_plural': 'Animals'},
        ),
        migrations.AlterModelOptions(
            name='animalclass',
            options={'verbose_name': 'AnimalClass', 'verbose_name_plural': 'AnimalClasses'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Country', 'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='fodder',
            options={'verbose_name': 'Fodder', 'verbose_name_plural': 'Fodders'},
        ),
        migrations.AlterModelOptions(
            name='placement',
            options={'verbose_name': 'Placement', 'verbose_name_plural': 'Placements'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.AlterModelOptions(
            name='species',
            options={'verbose_name': 'Species', 'verbose_name_plural': 'Species'},
        ),
        migrations.AlterModelOptions(
            name='staffer',
            options={'verbose_name': 'Staffer', 'verbose_name_plural': 'Staff'},
        ),
    ]
