# Generated by Django 4.2.1 on 2023-05-19 16:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_animal_options_alter_animalclass_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffer',
            name='phone_number',
            field=models.CharField(default='+375 (29) XXX-XX-XX', max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be in the format: '+375 (29) XXX-XX-XX'", regex='^\\+375 \\(\\d{2}\\) \\d{3}-\\d{2}-\\d{2}$')]),
        ),
    ]
