# Generated by Django 4.2.1 on 2023-05-21 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_staffer_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='placement',
            options={'ordering': ['name', 'number'], 'verbose_name': 'Placement', 'verbose_name_plural': 'Placements'},
        ),
    ]
