# Generated by Django 4.2.1 on 2023-05-23 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_placement_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='animal_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.animalclass'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.country'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='daily_feed',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='animal',
            name='fodder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.fodder'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='info',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='animal',
            name='placement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animals', to='main.placement'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='species',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.species'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='staffer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animals', to='main.staffer'),
        ),
    ]
